/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CombatDemoRouteImport } from './routes/combat.demo'
import { Route as CombatIdRouteImport } from './routes/combat.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CombatDemoRoute = CombatDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => CombatRoute,
} as any)
const CombatIdRoute = CombatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CombatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combat/$id': typeof CombatIdRoute
  '/combat/demo': typeof CombatDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combat/$id': typeof CombatIdRoute
  '/combat/demo': typeof CombatDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combat/$id': typeof CombatIdRoute
  '/combat/demo': typeof CombatDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/combat/$id' | '/combat/demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/combat/$id' | '/combat/demo'
  id: '__root__' | '/' | '/combat/$id' | '/combat/demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combat/demo': {
      id: '/combat/demo'
      path: '/demo'
      fullPath: '/combat/demo'
      preLoaderRoute: typeof CombatDemoRouteImport
      parentRoute: typeof CombatRoute
    }
    '/combat/$id': {
      id: '/combat/$id'
      path: '/$id'
      fullPath: '/combat/$id'
      preLoaderRoute: typeof CombatIdRouteImport
      parentRoute: typeof CombatRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
